services:
  database:
    image: postgres:latest
    env_file:
      - .env
    environment:
    - 'POSTGRES_DB=${DATABASE_NAME}'
    - 'POSTGRES_USER=${DATABASE_USER}'
    - 'POSTGRES_PASSWORD=${DATABASE_PASS}'
    ports:
      - '5433:5432'
  service:
    image: mspr4-2025/orders-service
    env_file:
      - .env
    ports:
      - '8081:8080'
    depends_on:
      - database